// frontend/src/lib/components/Header.svelte
<script lang="ts">
  export let brand: string;
  export let nav: { label: string; href: string }[] = [];
</script>

<header class="w-full bg-gradient-to-b from-black/40 to-transparent text-white backdrop-blur-sm">
  <div class="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
    <a href="/" class="flex items-center gap-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-white/70 rounded-md px-1">
      <span class="text-xl font-semibold tracking-tight">{brand}</span>
    </a>

    {#if nav && nav.length > 0}
      <nav aria-label="Primary" class="hidden gap-4 sm:flex">
        {#each nav as item (item.href)}
          <a
            href={item.href}
            class="rounded-md px-3 py-1.5 text-sm text-white/90 transition hover:bg-white/10 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-white/70"
            >{item.label}</a>
        {/each}
      </nav>
    {/if}
  </div>
</header>

// src/components/Header.tsx
'use client';

import React from 'react';
import Link from 'next/link';

export function Header() {
  return (
    <header className="border-b border-gray-200 bg-white">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex h-16 items-center justify-between">
          {/* Logo */}
          <div className="flex-shrink-0">
            <Link 
              href="/events" 
              className="text-xl font-bold text-gray-900 hover:text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 rounded"
            >
              TicketTock
            </Link>
          </div>

          {/* Navigation placeholder - will be expanded in subtask 2.2 */}
          <nav 
            role="navigation" 
            aria-label="Main navigation"
            className="hidden md:block"
          >
            <div className="flex space-x-8">
              <Link
                href="/events"
                className="text-gray-900 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
              >
                Events
              </Link>
              {/* More nav items will be added in subtask 2.2 */}
            </div>
          </nav>

          {/* Mobile menu button placeholder - will be expanded in subtask 2.3 */}
          <div className="md:hidden">
            <button
              type="button"
              className="text-gray-500 hover:text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 rounded-md p-2"
              aria-label="Open menu"
            >
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </header>
  );
}
